### ISSUE TITLE
Rosservice call issue with /ed/classify

### ISSUE THREAD

**Issue by LeoYong95** [tue-robotics/ed_tutorials#4]
Hi there, 

I am facing some issue currently regarding the rosserivce call to use ed_perception to identify the object on a table in a simulation. The service call example provided as follow,
```
 rosservice call /ed/classify "{perception_models_path: '/home/amigo/ros/indigo/system/src/ed_perception_models/models/robotics_testlabs', ids: ["486c8a807eeb4ba5b27ed53e5af9ad7e","486c8a807eeb4ba5b27ed53e5af9ad7e","486c8a807eeb4ba5b27ed53e5af9ad7e"], property: 'type', prior: {values: [],  probabilities: [], unknown_probability: 0.1}}
```
But when I ran this, I encounter the following error,

```
`ERROR: Incompatible arguments to call service:
No field name [prior]
Provided arguments are:
 * {'prior': {'probabilities': [], 'values': [], 'unknown_probability': 0.1}, 'perception_models_path': '/home/amigo/ros/indigo/system/src/ed_perception_models/models/robotics_testlabs', 'property': 'type', 'ids': []} (type dict)

Service arguments are: [ids unknown_probability]
`
```

I did a rostopic info to view the service, it output 
```
`Node: /ed
URI: rosrpc://192.168.1.101:46855
Type: ed_perception_msgs/Classify
Args: ids unknown_probability
`
```
the service only require ids and unknown_probability input.
So I tried to just add those two parameters and it did not output anything and with no error message.
```
`ids: []
posteriors: []
expected_values: []
expected_value_probabilities: []
error_msg: ''
`
```
I have made sure that ed_perception is installed and the simulation is connected. Is there a proper way to make the rosservice call to verify the entity?

**Comment by MatthijsBurgh** [comment]
@LeoYong95, The tutorials cleary needs an update.

The current service definition can be found [here](https://github.com/tue-robotics/ed_perception/blob/master/ed_perception_msgs/srv/Classify.srv). The request only contains `ids` and `unknown_probability` indeed.

Could you provide the result of the simple_query service call, a list of loaded plugins, preferably the config file, and the exact call to the classify service.

**Comment by MatthijsBurgh** [comment]
@LeoYong95 please respond not later than April 3rd, Otherwise I will close this issue.
